# Generated by Django 5.0.6 on 2024-06-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_dataexample_language_nullexample_simple_framework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='lenguage',
            new_name='language',
        ),
    ]
